# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Parsing
subtitle: > # ignore newlines until "description:"
    Course web page, winter semester 2020/2021 -
    <a href="http://www.sfs.uni-tuebingen.de">SfS</a>,
    <a href="http://uni-tuebingen.de/">University of Tübingen</a>
description: > # ignore newlines until "baseurl:"
    This is the course web page for 
    Parsing course
    taught in the linguistic department (SfS), University of Tübingen.
baseurl: ""
url: "https://iscl-parsing202.github.io"
github_username: iscl-parsing202
encoding: utf-8
future: true

# Build settings
markdown: kramdown
